name: "release"

on:
  push:
    branches:
      - "main"

jobs:
  build_and_release:
    name: build and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies (npm)
        run: npm install

      - name: Run tests
        run: ./run tests

      - name: Run build
        run: ./run build

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            dist/dist.tar.gz
